server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: book-service
          uri: http://localhost:8081
          predicates:
            - Path=/books/**
        - id: loan-service
          uri: http://localhost:8082
          predicates:
            - Path=/loans/**